# Application Configuration
# Generated by hostcfg using Sprig template functions
# DO NOT EDIT MANUALLY

app:
  # String manipulation
  name: {{ .var.app_name | upper }}
  slug: {{ .var.app_name | lower | replace " " "-" }}
  display_name: {{ .var.app_name | title }}

  # Environment with default fallback
  environment: {{ .var.environment | default "development" }}
  debug: {{ ternary true false (eq .var.environment "development") }}

server:
  host: {{ .var.server_host | default "0.0.0.0" }}
  port: {{ .var.server_port }}
  # Conditionally include TLS settings
  {{- if .var.tls_enabled }}
  tls:
    enabled: true
    cert_file: /etc/ssl/certs/{{ .var.app_name | lower }}.crt
    key_file: /etc/ssl/private/{{ .var.app_name | lower }}.key
  {{- else }}
  tls:
    enabled: false
  {{- end }}

# Database configuration from map
database:
  {{- range $key, $value := .var.database }}
  {{ $key }}: {{ $value }}
  {{- end }}

# Feature flags from list
features:
  {{- range .var.features }}
  - {{ . }}
  {{- end }}
  {{- if empty .var.features }}
  # No features enabled
  {{- end }}

# Users with iteration index
users:
  {{- range $index, $user := .var.users }}
  - id: {{ $index }}
    username: {{ $user }}
    email: {{ $user | lower }}@{{ $.var.domain }}
  {{- end }}

# Encoding examples
secrets:
  # Base64 encoded API key (for demonstration)
  api_key_encoded: {{ .var.api_key | b64enc }}
  # SHA256 hash of secret (for integrity checking)
  secret_hash: {{ .var.api_key | sha256sum }}

# JSON embedded configuration
metadata: {{ .var.metadata | toJson }}

# Pretty-printed JSON (with proper indentation)
extended_config: |
{{ .var.metadata | toPrettyJson | indent 2 }}

# YAML conversion
labels:
{{ .var.labels | toYaml | indent 2 }}

# Conditional blocks with multiple conditions
logging:
  level: {{ .var.log_level | default "info" }}
  {{- if and .var.log_to_file (ne .var.environment "development") }}
  file: /var/log/{{ .var.app_name | lower }}/app.log
  rotate: true
  max_size: 100M
  {{- end }}
  {{- if or (eq .var.environment "development") (eq .var.environment "staging") }}
  console: true
  colorize: true
  {{- end }}

# Required field validation (will fail if empty)
# organization: {{ .var.organization | required "organization is required" }}

# Date/time (current timestamp)
generated_at: {{ now | date "2006-01-02T15:04:05Z07:00" }}

# String trimming and formatting
paths:
  config: {{ .var.config_path | trimSuffix "/" }}/config
  data: {{ .var.config_path | trimSuffix "/" }}/data
  logs: {{ .var.config_path | trimSuffix "/" }}/logs

# List operations
allowed_origins:
  {{- $origins := list "http://localhost:3000" }}
  {{- if ne .var.environment "development" }}
    {{- $origins = append $origins (printf "https://%s" .var.domain) }}
    {{- $origins = append $origins (printf "https://www.%s" .var.domain) }}
  {{- end }}
  {{- range $origins | uniq }}
  - {{ . }}
  {{- end }}

# Multi-line string with proper indentation
banner: |
{{ .var.banner | default "Welcome to the application" | indent 2 }}

# Dict creation and merging
{{- $defaults := dict "timeout" "30s" "retries" 3 "backoff" "exponential" }}
{{- $custom := dict "timeout" "60s" "max_connections" 100 }}
{{- $merged := merge $custom $defaults }}
http_client:
  {{- range $key, $value := $merged }}
  {{ $key }}: {{ $value }}
  {{- end }}
