# Application Configuration
# Generated by hostcfg with system facts
# DO NOT EDIT MANUALLY

# System information from facts
system:
  hostname: {{ .fact.hostname }}
  fqdn: {{ .fact.fqdn }}
  arch: {{ .fact.arch }}

  os:
    name: {{ .fact.os.name }}
    family: {{ .fact.os.family }}
    distribution: {{ .fact.os.distribution }}
    version: {{ .fact.os.distribution_version }}

  user:
    name: {{ .fact.user.name }}
    home: {{ .fact.user.home }}
    uid: {{ .fact.user.uid }}
    gid: {{ .fact.user.gid }}

# OS-specific settings using conditionals
{{- if eq .fact.os.family "debian" }}
package_manager: apt
update_command: apt-get update && apt-get upgrade -y
{{- else if eq .fact.os.family "redhat" }}
package_manager: dnf
update_command: dnf upgrade -y
{{- else if eq .fact.os.family "arch" }}
package_manager: pacman
update_command: pacman -Syu --noconfirm
{{- else if eq .fact.os.family "darwin" }}
package_manager: brew
update_command: brew update && brew upgrade
{{- else }}
package_manager: unknown
update_command: echo "Unknown package manager"
{{- end }}

# Architecture-specific settings
{{- if eq .fact.arch "amd64" }}
binary_suffix: x86_64
{{- else if eq .fact.arch "arm64" }}
binary_suffix: aarch64
{{- else }}
binary_suffix: {{ .fact.arch }}
{{- end }}

# Paths derived from facts
paths:
  config: {{ .fact.user.home }}/.config/{{ .var.app_name }}
  data: {{ .fact.user.home }}/.local/share/{{ .var.app_name }}
  cache: {{ .fact.user.home }}/.cache/{{ .var.app_name }}
  logs: /var/log/{{ .var.app_name }}

# Generated metadata
generated_at: {{ now | date "2006-01-02T15:04:05Z07:00" }}
generated_on: {{ .fact.hostname }}
generated_by: {{ .fact.user.name }}
