# Nginx upstream configuration
# Generated by hostcfg

# Upstream for {{ .var.app_name | lower | replace " " "-" }}
upstream {{ .var.app_name | lower | replace " " "_" }}_backend {
    {{- $port := .var.server_port | default "8080" }}
    {{- $servers := list "127.0.0.1" }}
    {{- range $servers }}
    server {{ . }}:{{ $port }};
    {{- end }}

    # Load balancing configuration
    {{- if eq .var.environment "production" }}
    least_conn;
    keepalive 32;
    {{- end }}
}

server {
    {{- if .var.tls_enabled }}
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /etc/ssl/certs/{{ .var.domain }}.crt;
    ssl_certificate_key /etc/ssl/private/{{ .var.domain }}.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;
    {{- else }}
    listen 80;
    listen [::]:80;
    {{- end }}

    server_name {{ .var.domain }} www.{{ .var.domain }};

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    {{- if .var.tls_enabled }}
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    {{- end }}

    # Logging
    access_log /var/log/nginx/{{ .var.app_name | lower | replace " " "-" }}_access.log;
    error_log /var/log/nginx/{{ .var.app_name | lower | replace " " "-" }}_error.log {{ .var.log_level | default "warn" }};

    location / {
        proxy_pass http://{{ .var.app_name | lower | replace " " "_" }}_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        {{- if eq .var.environment "production" }}
        proxy_set_header Connection "";
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        {{- end }}
    }

    # Health check endpoint
    location /health {
        proxy_pass http://{{ .var.app_name | lower | replace " " "_" }}_backend/health;
        access_log off;
    }

    {{- if or (eq .var.environment "development") (eq .var.environment "staging") }}

    # Debug endpoints (non-production only)
    location /debug {
        proxy_pass http://{{ .var.app_name | lower | replace " " "_" }}_backend/debug;
        # Restrict to internal networks
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
    }
    {{- end }}
}

{{- if and .var.tls_enabled (ne .var.environment "development") }}

# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name {{ .var.domain }} www.{{ .var.domain }};
    return 301 https://$server_name$request_uri;
}
{{- end }}
